
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tandons
 */
public class Cash extends javax.swing.JFrame {

    /**
     * Creates new form Cash
     */
    public Cash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    Boolean PostTransaction = true;
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupDepositPayment = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxFunction = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jXDatePickerTransactionDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTransactionId = new javax.swing.JTextField();
        jRadioButtonDeposit = new javax.swing.JRadioButton();
        jRadioButtonPayment = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldAccountNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldAccountName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldAccountBalance = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldTransactionAmount = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldAmt100 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldCount2000 = new javax.swing.JTextField();
        jTextFieldAmt2000 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldCount500 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldCount200 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldAmt500 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldCount100 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldAmt200 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jTextFieldCount50 = new javax.swing.JTextField();
        jTextFieldCount20 = new javax.swing.JTextField();
        jTextFieldCount10 = new javax.swing.JTextField();
        jTextFieldCount5 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextFieldAmt50 = new javax.swing.JTextField();
        jTextFieldAmt20 = new javax.swing.JTextField();
        jTextFieldAmt10 = new javax.swing.JTextField();
        jTextFieldAmt5 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jTextFieldDenomAmount = new javax.swing.JTextField();
        jButtonValidate = new javax.swing.JButton();
        jButtonPostTransaction = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextFieldBalanceAfterPosting = new javax.swing.JTextField();
        jTextFieldTransactionParticulars = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextFieldContraAccountBalance = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextFieldContraAccountBalanceAfterPosting = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel33 = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BankUpon - Cash Deposit and Payment");
        setFocusCycleRoot(false);
        setSize(new java.awt.Dimension(0, 0));

        jLabel4.setFont(new java.awt.Font("Algerian", 1, 30)); // NOI18N
        jLabel4.setText("CASH - DEPOSIT and Payment");
        jLabel4.setToolTipText("");

        jComboBoxFunction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Add", "Inquire" }));

        jLabel1.setText("Transaction Date");

        jLabel2.setText("Transaction Id");

        buttonGroupDepositPayment.add(jRadioButtonDeposit);
        jRadioButtonDeposit.setSelected(true);
        jRadioButtonDeposit.setText("Deposit");

        buttonGroupDepositPayment.add(jRadioButtonPayment);
        jRadioButtonPayment.setText("Payment");

        jLabel3.setText("Account Number");

        jLabel5.setText("Account Name");

        jTextFieldAccountName.setEditable(false);
        jTextFieldAccountName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextFieldAccountName.setEnabled(false);

        jLabel6.setText("Account Balance");

        jTextFieldAccountBalance.setEditable(false);
        jTextFieldAccountBalance.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextFieldAccountBalance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldAccountBalance.setEnabled(false);

        jLabel7.setText("Transaction Amount");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Currency Denominations");

        jLabel9.setText("Total Amount");

        jTextFieldAmt100.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldAmt100.setEnabled(false);

        jLabel10.setText("Rs. 2000   x");

        jTextFieldCount2000.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldCount2000.setText("0");

        jTextFieldAmt2000.setEditable(false);
        jTextFieldAmt2000.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldAmt2000.setEnabled(false);

        jLabel11.setText("=");

        jLabel12.setText("Rs.   500   x");

        jTextFieldCount500.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel13.setText("=");

        jLabel14.setText("Rs.   200   x");

        jTextFieldCount200.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldCount200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCount200ActionPerformed(evt);
            }
        });

        jLabel15.setText("=");

        jTextFieldAmt500.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldAmt500.setEnabled(false);
        jTextFieldAmt500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAmt500ActionPerformed(evt);
            }
        });

        jLabel16.setText("Rs.   100   x");

        jTextFieldCount100.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel17.setText("=");

        jTextFieldAmt200.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldAmt200.setEnabled(false);

        jLabel18.setText("Notes");

        jLabel19.setText("Rs.     50   x");

        jLabel20.setText("Rs.     20   x");

        jLabel21.setText("Rs.      10  x");

        jLabel22.setText("Rs.       5  x");

        jTextFieldCount50.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldCount50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCount50ActionPerformed(evt);
            }
        });

        jTextFieldCount20.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextFieldCount10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextFieldCount5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel23.setText("=");

        jLabel24.setText("=");

        jLabel25.setText("=");

        jLabel26.setText("=");

        jTextFieldAmt50.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldAmt50.setEnabled(false);
        jTextFieldAmt50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAmt50ActionPerformed(evt);
            }
        });

        jTextFieldAmt20.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldAmt20.setEnabled(false);
        jTextFieldAmt20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAmt20ActionPerformed(evt);
            }
        });

        jTextFieldAmt10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldAmt10.setEnabled(false);
        jTextFieldAmt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAmt10ActionPerformed(evt);
            }
        });

        jTextFieldAmt5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldAmt5.setEnabled(false);
        jTextFieldAmt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAmt5ActionPerformed(evt);
            }
        });

        jTextFieldDenomAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldDenomAmount.setEnabled(false);
        jTextFieldDenomAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDenomAmountActionPerformed(evt);
            }
        });

        jButtonValidate.setText("Validate");
        jButtonValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidateActionPerformed(evt);
            }
        });

        jButtonPostTransaction.setText("Post Transaction");
        jButtonPostTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPostTransactionActionPerformed(evt);
            }
        });

        jLabel27.setText("Balance after posting");

        jLabel28.setText("Transaction Particulars");

        jTextFieldBalanceAfterPosting.setEditable(false);
        jTextFieldBalanceAfterPosting.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextFieldBalanceAfterPosting.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldBalanceAfterPosting.setEnabled(false);

        jLabel29.setText("Cash in Hand Balance");

        jTextFieldContraAccountBalance.setEditable(false);
        jTextFieldContraAccountBalance.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextFieldContraAccountBalance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldContraAccountBalance.setEnabled(false);

        jLabel30.setText("Cash in Hand Balance after Posting");

        jTextFieldContraAccountBalanceAfterPosting.setEditable(false);
        jTextFieldContraAccountBalanceAfterPosting.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextFieldContraAccountBalanceAfterPosting.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldContraAccountBalanceAfterPosting.setEnabled(false);

        jLabel33.setText("Transaction Type");

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(378, 378, 378)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(1695, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel27))
                                .addGap(107, 107, 107)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldAccountBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldTransactionAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldBalanceAfterPosting, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldContraAccountBalanceAfterPosting, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldTransactionParticulars, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jTextFieldContraAccountBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(280, 280, 280)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jButtonValidate)
                                .addGap(50, 50, 50)
                                .addComponent(jButtonPostTransaction)
                                .addGap(66, 66, 66)
                                .addComponent(jButtonExit)))
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel14)
                                                .addComponent(jLabel16))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel21))))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldCount50, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldCount500, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldCount200, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldCount100, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldCount2000, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldCount20, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCount10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCount5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel23)
                                                    .addComponent(jLabel25))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jTextFieldAmt10, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextFieldAmt5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jTextFieldAmt20, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextFieldAmt500, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextFieldAmt200, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextFieldAmt100, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextFieldAmt50, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jTextFieldDenomAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(jTextFieldAmt2000, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(203, 203, 203)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel26))
                                        .addGap(249, 249, 249))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(10, 10, 10))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1067, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addGap(126, 126, 126)
                                        .addComponent(jRadioButtonDeposit)
                                        .addGap(33, 33, 33)
                                        .addComponent(jRadioButtonPayment))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBoxFunction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(95, 95, 95)
                                        .addComponent(jLabel1)
                                        .addGap(30, 30, 30)
                                        .addComponent(jXDatePickerTransactionDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldTransactionId, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(222, 222, 222)
                                        .addComponent(jLabel8)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1750, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(715, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(908, 908, 908)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel31)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel32)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel38)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxFunction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jXDatePickerTransactionDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldTransactionId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel10))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12)
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel14)
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel16)
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel19)
                                            .addComponent(jTextFieldCount50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel24))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel20)
                                            .addComponent(jTextFieldCount20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel23))
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel21)
                                            .addComponent(jTextFieldCount10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel22)
                                            .addComponent(jTextFieldCount5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel25)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextFieldCount2000, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldAmt2000, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(jTextFieldAmt500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jTextFieldCount500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel11))
                                                .addGap(7, 7, 7)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jTextFieldCount200, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel15)
                                                    .addComponent(jTextFieldAmt200, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextFieldAmt100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jTextFieldCount100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel17)))))
                                        .addGap(27, 27, 27)
                                        .addComponent(jTextFieldAmt50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldAmt20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldAmt10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jTextFieldAmt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jTextFieldDenomAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(367, 367, 367)
                        .addComponent(jLabel26)
                        .addGap(282, 282, 282)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonDeposit)
                            .addComponent(jRadioButtonPayment)
                            .addComponent(jLabel33))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldAccountBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTransactionAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jTextFieldBalanceAfterPosting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(jTextFieldTransactionParticulars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(jTextFieldContraAccountBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(jTextFieldContraAccountBalanceAfterPosting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonValidate)
                            .addComponent(jButtonPostTransaction)
                            .addComponent(jButtonExit))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(373, 373, 373)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel31)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel32)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel38)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAmt500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAmt500ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAmt500ActionPerformed

    private void jTextFieldCount50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCount50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCount50ActionPerformed

    private void jTextFieldAmt50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAmt50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAmt50ActionPerformed

    private void jTextFieldAmt20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAmt20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAmt20ActionPerformed

    private void jTextFieldAmt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAmt10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAmt10ActionPerformed

    private void jTextFieldAmt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAmt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAmt5ActionPerformed

    private void jTextFieldDenomAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDenomAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDenomAmountActionPerformed
private boolean validateCashForm(){
      if (jTextFieldCount2000.getText().isEmpty()) {
        jTextFieldCount2000.setText("0"); 
      }
      if (jTextFieldCount500.getText().isEmpty()) {
        jTextFieldCount500.setText("0"); 
      }
      if (jTextFieldCount200.getText().isEmpty()) {
        jTextFieldCount200.setText("0"); 
      }
      if (jTextFieldCount100.getText().isEmpty()) {
        jTextFieldCount100.setText("0"); 
      }
      if (jTextFieldCount50.getText().isEmpty()) {
        jTextFieldCount50.setText("0"); 
      }
      if (jTextFieldCount20.getText().isEmpty()) {
        jTextFieldCount20.setText("0"); 
      }
      if (jTextFieldCount10.getText().isEmpty()) {
        jTextFieldCount10.setText("0"); 
      }
      if (jTextFieldCount5.getText().isEmpty()) {
        jTextFieldCount5.setText("0"); 
      }
      if (jTextFieldTransactionAmount.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this,"Transaction Amount not Entered"); 
        return false;
      }
      return true;
}
    private void jButtonValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidateActionPerformed
       Calendar cal = Calendar.getInstance();
        
       jXDatePickerTransactionDate.setDate(cal.getTime());
       
            
       if (validateCashForm())
        {
            
            if (jComboBoxFunction.getSelectedItem() == "Add" )  
{
    String AccountNumber=jTextFieldAccountNumber.getText(); 
    if (AccountNumber.isEmpty()) {
        JOptionPane.showMessageDialog(this,"Account Number not Entered");
    }
    else
    { 
     try { Class.forName("java.sql.DriverManager"); 
Connection con = (Connection) DriverManager.getConnection (BankUponDataSource.CONNECTIONSTRING, BankUponDataSource.USERID, BankUponDataSource.PASSWD);   

Statement stmt = (Statement) con.createStatement();
     
String query="select AccountName, AccountBalance, ClosureDate from Accounts where AccountNumber = '"+AccountNumber+"';";      

String AccountClosureDate = "";

ResultSet rs = stmt.executeQuery(query);
if (rs.next()) {
    
    jTextFieldAccountName.setText(rs.getString("AccountName"));  
    jTextFieldAccountBalance.setText(rs.getString("AccountBalance"));  
    //AccountClosureDate = rs.getDate("ClosureDate").toString();
    //if (! AccountClosureDate.isEmpty())
    //{
    //    PostTransaction = false;
    //    JOptionPane.showMessageDialog(this,"Account is closed !");
    //}  
}    
else 
    JOptionPane.showMessageDialog(this,"Invalid Account Number!");
}
catch (Exception e) 
{ JOptionPane.showMessageDialog (this, e.getMessage());   } 
}
}
            
            
            
        int Amt2000 = 2000 * Integer.parseInt(jTextFieldCount2000.getText());
        jTextFieldAmt2000.setText(Integer.toString(Amt2000));
        int Amt500 = 500 * Integer.parseInt(jTextFieldCount500.getText());
        jTextFieldAmt500.setText(Integer.toString(Amt500));
        int Amt200 = 200 * Integer.parseInt(jTextFieldCount200.getText());
        jTextFieldAmt200.setText(Integer.toString(Amt200));
        int Amt100 = 100 * Integer.parseInt(jTextFieldCount100.getText());
        jTextFieldAmt100.setText(Integer.toString(Amt100));
        int Amt50 = 50 * Integer.parseInt(jTextFieldCount50.getText());
        jTextFieldAmt50.setText(Integer.toString(Amt50));
        int Amt20 = 20 * Integer.parseInt(jTextFieldCount20.getText());
        jTextFieldAmt20.setText(Integer.toString(Amt20));
        int Amt10 = 10 * Integer.parseInt(jTextFieldCount10.getText());
        jTextFieldAmt10.setText(Integer.toString(Amt10));
        int Amt5 = 5 * Integer.parseInt(jTextFieldCount5.getText());
        jTextFieldAmt5.setText(Integer.toString(Amt5));
        
        int DenomAmount = Amt2000+Amt500+Amt200+Amt100+Amt50+Amt20+Amt10+Amt5;
        jTextFieldDenomAmount.setText(Integer.toString(DenomAmount));
        
        
        double TransactionAmount = Double.parseDouble(jTextFieldTransactionAmount.getText());
        
        if (TransactionAmount != DenomAmount)
            JOptionPane.showMessageDialog(this,"Denominations Total not tallying with Transaction Amount. Please check.");
        
        }
    }//GEN-LAST:event_jButtonValidateActionPerformed

    private void jButtonPostTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPostTransactionActionPerformed
    
    DateFormat format = new SimpleDateFormat("yyyy-MM-dd");
    String TransactionDate = format.format(jXDatePickerTransactionDate.getDate());
    String TransactionType = "";
    String AccountNumber=jTextFieldAccountNumber.getText();
    String TransactionParticulars=jTextFieldTransactionParticulars.getText();        
    Double AccountBalance = Double.parseDouble(jTextFieldAccountBalance.getText());
    Double TransactionAmount = Double.parseDouble(jTextFieldTransactionAmount.getText());
    String DebitCredit = "", ContraDebitCredit = "";
    Double BalanceAfterPosting = 0.0;
    String ContraAccountNumber = "1";
    String ContraTransactionParticulars = "";
    Double ContraAccountBalance = 0.0;
    Double ContraAccountBalanceAfterPosting = 0.0;
    Date ContraAccountClosureDate = null;
    
    
    
    ResultSet rs = null;
       try { Class.forName("java.sql.DriverManager"); 
Connection con = (Connection) DriverManager.getConnection (BankUponDataSource.CONNECTIONSTRING, BankUponDataSource.USERID, BankUponDataSource.PASSWD);   

    Statement stmt = (Statement) con.createStatement();
    String query="select AccountName, AccountBalance, ClosureDate from Accounts where AccountNumber = "+ContraAccountNumber+";";
     rs = stmt.executeQuery(query);
if (rs.next()) {
    
        jTextFieldContraAccountBalance.setText(rs.getString("AccountBalance"));
        
        ContraAccountClosureDate = rs.getDate("ClosureDate");
        //if (!ContraAccountClosureDate.toString().isEmpty()){
        //   PostTransaction = false; 
        //   JOptionPane.showMessageDialog(this,"Cash Account is closed !");
        //}
        
}      
else 
{
    JOptionPane.showMessageDialog(this,"Invalid Cash Account Number!");
}
    
ContraAccountBalance = Double.parseDouble(jTextFieldContraAccountBalance.getText());

    if (jRadioButtonDeposit.isSelected())
    {
        TransactionType="CashDeposit";
        DebitCredit = "C";
        ContraDebitCredit = "D";
        BalanceAfterPosting = AccountBalance + TransactionAmount;
        ContraAccountBalanceAfterPosting = ContraAccountBalance - TransactionAmount;
        ContraTransactionParticulars = "Cash Deposited";
    }
    if (jRadioButtonPayment.isSelected())
    {
        DebitCredit = "D";
        ContraDebitCredit = "C";
        TransactionType="CashPayment";
        ContraTransactionParticulars = "Cash Paid";
        
        if (AccountBalance >= TransactionAmount)
            BalanceAfterPosting = AccountBalance - TransactionAmount;
        else
        {
            PostTransaction = false;
            JOptionPane.showMessageDialog(this,"Insuffecient Account Balance");
        }
        if (ContraAccountBalance * (-1) >= TransactionAmount)
            ContraAccountBalanceAfterPosting = ContraAccountBalance + TransactionAmount;
        else
        {
            PostTransaction = false;
            JOptionPane.showMessageDialog(this,"Insuffecient Cash in Hand Account Balance");
        }
    }
 
    if (PostTransaction)
    {
    jTextFieldBalanceAfterPosting.setText(Double.toString(BalanceAfterPosting));
    jTextFieldContraAccountBalanceAfterPosting.setText(Double.toString(ContraAccountBalanceAfterPosting));
        
    
    query="INSERT INTO transactions (TransactionDate, TransactionType) VALUES  ('"+TransactionDate+"','"+TransactionType+"');";      
long key = -1L;

stmt.executeUpdate(query, Statement.RETURN_GENERATED_KEYS);
rs = stmt.getGeneratedKeys();

if (rs != null && rs.next()) {
    key = rs.getLong(1);
    
}


query="INSERT INTO TransactionDetails (TransactionId, AccountNumber, TransactionParticulars, DebitCredit, TransactionAmount, BalanceAfterPosting) VALUES  ('"+key+"','"+AccountNumber+"','"+TransactionParticulars+"','"+DebitCredit+"','"+TransactionAmount+"','"+BalanceAfterPosting+"');";      

stmt.executeUpdate(query);


query="INSERT INTO TransactionDetails (TransactionId, AccountNumber, TransactionParticulars, DebitCredit, TransactionAmount, BalanceAfterPosting) VALUES  ('"+key+"','"+ContraAccountNumber+"','"+ContraTransactionParticulars+"','"+ContraDebitCredit+"','"+TransactionAmount+"','"+ContraAccountBalanceAfterPosting+"');";      

stmt.executeUpdate(query);

query="update accounts set AccountBalance = "+BalanceAfterPosting+" where AccountNumber = '"+AccountNumber+"';";     
stmt.executeUpdate(query);

query="update accounts set AccountBalance = "+ContraAccountBalanceAfterPosting+" where AccountNumber = '"+ContraAccountNumber+"';";     
stmt.executeUpdate(query);

JOptionPane.showMessageDialog(this,"Transaction created " + key);  
jTextFieldTransactionId.setText(Long.toString(key));      

    }
    
}
catch (Exception e) 
{ JOptionPane.showMessageDialog (this, e.getMessage());   
}    }//GEN-LAST:event_jButtonPostTransactionActionPerformed

    private void jTextFieldCount200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCount200ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCount200ActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
           this.dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupDepositPayment;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonPostTransaction;
    private javax.swing.JButton jButtonValidate;
    private javax.swing.JComboBox<String> jComboBoxFunction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButtonDeposit;
    private javax.swing.JRadioButton jRadioButtonPayment;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextFieldAccountBalance;
    private javax.swing.JTextField jTextFieldAccountName;
    private javax.swing.JTextField jTextFieldAccountNumber;
    private javax.swing.JTextField jTextFieldAmt10;
    private javax.swing.JTextField jTextFieldAmt100;
    private javax.swing.JTextField jTextFieldAmt20;
    private javax.swing.JTextField jTextFieldAmt200;
    private javax.swing.JTextField jTextFieldAmt2000;
    private javax.swing.JTextField jTextFieldAmt5;
    private javax.swing.JTextField jTextFieldAmt50;
    private javax.swing.JTextField jTextFieldAmt500;
    private javax.swing.JTextField jTextFieldBalanceAfterPosting;
    private javax.swing.JTextField jTextFieldContraAccountBalance;
    private javax.swing.JTextField jTextFieldContraAccountBalanceAfterPosting;
    private javax.swing.JTextField jTextFieldCount10;
    private javax.swing.JTextField jTextFieldCount100;
    private javax.swing.JTextField jTextFieldCount20;
    private javax.swing.JTextField jTextFieldCount200;
    private javax.swing.JTextField jTextFieldCount2000;
    private javax.swing.JTextField jTextFieldCount5;
    private javax.swing.JTextField jTextFieldCount50;
    private javax.swing.JTextField jTextFieldCount500;
    private javax.swing.JTextField jTextFieldDenomAmount;
    private javax.swing.JTextField jTextFieldTransactionAmount;
    private javax.swing.JTextField jTextFieldTransactionId;
    private javax.swing.JTextField jTextFieldTransactionParticulars;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerTransactionDate;
    // End of variables declaration//GEN-END:variables
}
