/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCustomerMaintenance = new javax.swing.JMenuItem();
        jMenuItemAccountMaintenance = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemCash = new javax.swing.JMenuItem();
        jMenuItemTransfer = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemLedger = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemUserMaintenance = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItemExitYes = new javax.swing.JMenuItem();
        jMenuItemExitNo = new javax.swing.JMenuItem();

        jMenu7.setText("jMenu7");

        jMenu8.setText("jMenu8");

        jMenu9.setText("jMenu9");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jMenu10.setText("jMenu10");

        jMenuItem3.setText("jMenuItem3");

        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem4.setText("jCheckBoxMenuItem4");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BankUpon - Main Menu");

        jMenu1.setText("Entity");

        jMenuItemCustomerMaintenance.setText("Customer Maintenance");
        jMenuItemCustomerMaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCustomerMaintenanceActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCustomerMaintenance);

        jMenuItemAccountMaintenance.setText("Accounts Maintenance");
        jMenuItemAccountMaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAccountMaintenanceActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAccountMaintenance);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transactions");

        jMenuItemCash.setText("Cash Receipt and Payment");
        jMenuItemCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCashActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemCash);

        jMenuItemTransfer.setText("Transfer");
        jMenuItemTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTransferActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemTransfer);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Customer Service");

        jMenuItemLedger.setText("Account Ledger");
        jMenuItemLedger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLedgerActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemLedger);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Reports");
        jMenuBar1.add(jMenu5);

        jMenu3.setText("Administration");

        jMenuItemUserMaintenance.setText("User Maintenance");
        jMenuItemUserMaintenance.setToolTipText("");
        jMenuItemUserMaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUserMaintenanceActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemUserMaintenance);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("Exit");

        jMenuItemExitYes.setText("Yes");
        jMenuItemExitYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitYesActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemExitYes);

        jMenuItemExitNo.setText("No");
        jMenu6.add(jMenuItemExitNo);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1014, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAccountMaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAccountMaintenanceActionPerformed
new AccountMaintenance().setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAccountMaintenanceActionPerformed

    private void jMenuItemCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCashActionPerformed
       new Cash().setVisible(true);  
    }//GEN-LAST:event_jMenuItemCashActionPerformed

    private void jMenuItemTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTransferActionPerformed
    new Transfer().setVisible(true);      
    }//GEN-LAST:event_jMenuItemTransferActionPerformed

    private void jMenuItemCustomerMaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCustomerMaintenanceActionPerformed
       new CustomerMaintenance().setVisible(true);        
    }//GEN-LAST:event_jMenuItemCustomerMaintenanceActionPerformed

    private void jMenuItemUserMaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUserMaintenanceActionPerformed
        new UserMaintenance().setVisible(true);     
    }//GEN-LAST:event_jMenuItemUserMaintenanceActionPerformed

    private void jMenuItemExitYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitYesActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItemExitYesActionPerformed

    private void jMenuItemLedgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLedgerActionPerformed
        new AccountLedger().setVisible(true);   
    }//GEN-LAST:event_jMenuItemLedgerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemAccountMaintenance;
    private javax.swing.JMenuItem jMenuItemCash;
    private javax.swing.JMenuItem jMenuItemCustomerMaintenance;
    private javax.swing.JMenuItem jMenuItemExitNo;
    private javax.swing.JMenuItem jMenuItemExitYes;
    private javax.swing.JMenuItem jMenuItemLedger;
    private javax.swing.JMenuItem jMenuItemTransfer;
    private javax.swing.JMenuItem jMenuItemUserMaintenance;
    // End of variables declaration//GEN-END:variables
}
